import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useNavigate, useParams } from "react-router-dom";
import type { Evaluation, Period, User } from "@kpi/contracts";
import { useActor } from "../context/actor-context";
import { api, json } from "../lib/api";
import { Badge, Button, Empty, ErrorState, Input, Loading, PageHeader, Select } from "../components/ui";

export function TeamEvaluationsPage() {
  const { actorId, actor } = useActor(); const client = useQueryClient(); const navigate = useNavigate(); const [periodId, setPeriodId] = useState(""); const [status, setStatus] = useState("all");
  const users = useQuery({ queryKey: ["users", actorId], queryFn: () => api<User[]>("/users") });
  const periods = useQuery({ queryKey: ["periods", actorId], queryFn: () => api<Period[]>("/periods") });
  const evaluations = useQuery({ queryKey: ["evaluations", actorId], queryFn: () => api<Evaluation[]>("/evaluations") });
  useEffect(() => { if (!periodId && periods.data) setPeriodId(periods.data.find((item) => item.status === "Active")?.id ?? periods.data[0]?.id ?? ""); }, [periodId, periods.data]);
  const create = useMutation({ mutationFn: (userId: string) => api<Evaluation>("/evaluations", json("POST", { userId, periodId })), onSuccess: (value) => { void client.invalidateQueries(); navigate(`/evaluations/${value.id}`); } });
  if (users.isLoading || periods.isLoading || evaluations.isLoading) return <Loading />; if (users.error || periods.error || evaluations.error) return <ErrorState error={users.error ?? periods.error ?? evaluations.error} />;
  if (!actor?.isManager) return <><PageHeader title="Team evaluations" description="Evaluation management is available to managers." /><Empty title="Manager access required" text="Switch to a manager identity to evaluate a team." /></>;
  const rows = users.data?.filter((user) => user.id !== actorId).map((user) => ({ user, evaluation: evaluations.data?.find((item) => item.userId === user.id && item.periodId === periodId) ?? null })).filter((row) => status === "all" || (status === "pending" ? !row.evaluation || row.evaluation.status === "draft" : row.evaluation?.status === status)) ?? [];
  return <><PageHeader title="Team evaluations" description="Create, complete, submit, and close evaluations across your reporting tree." /><div className="mb-5 flex flex-wrap gap-3"><Select className="max-w-56" value={periodId} onChange={(e) => setPeriodId(e.target.value)}>{periods.data?.map((period) => <option key={period.id} value={period.id}>{period.name} · {period.status}</option>)}</Select><Select className="max-w-48" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="submitted">Submitted</option><option value="closed">Closed</option></Select></div>{create.error && <div className="mb-4"><ErrorState error={create.error} /></div>}<div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead><tr><th className="table-head">Employee</th><th className="table-head">Role</th><th className="table-head">Score</th><th className="table-head">Status</th><th className="table-head"></th></tr></thead><tbody>{rows.map(({ user, evaluation }) => <tr key={user.id}><td className="table-cell font-semibold text-gray-900">{user.name}</td><td className="table-cell">{user.title}</td><td className="table-cell font-semibold">{evaluation ? `${evaluation.totalScore.toFixed(2)}%` : "—"}</td><td className="table-cell"><Badge tone={evaluation?.status === "submitted" || evaluation?.status === "closed" ? "green" : "amber"}>{evaluation?.status ?? "Not started"}</Badge></td><td className="table-cell text-right">{evaluation ? <Link className="font-semibold text-brand-700" to={`/evaluations/${evaluation.id}`}>Open evaluation</Link> : <Button variant="secondary" disabled={create.isPending || periods.data?.find((item) => item.id === periodId)?.status !== "Active"} onClick={() => create.mutate(user.id)}>Create</Button>}</td></tr>)}</tbody></table></div></div></>;
}

export function EvaluationPage() {
  const { id = "" } = useParams(); const { actorId, actor } = useActor(); const client = useQueryClient();
  const evaluation = useQuery({ queryKey: ["evaluation", actorId, id], queryFn: () => api<Evaluation>(`/evaluations/${id}`) });
  const users = useQuery({ queryKey: ["users", actorId], queryFn: () => api<User[]>("/users") });
  const periods = useQuery({ queryKey: ["periods", actorId], queryFn: () => api<Period[]>("/periods") });
  const [values, setValues] = useState<Record<string, number | null>>({});
  useEffect(() => { if (evaluation.data) setValues(Object.fromEntries(evaluation.data.kpis.map((kpi) => [kpi.key, kpi.actualValue]))); }, [evaluation.data]);
  const refresh = () => { void client.invalidateQueries({ queryKey: ["evaluation"] }); void client.invalidateQueries({ queryKey: ["evaluations"] }); void client.invalidateQueries({ queryKey: ["dashboard"] }); };
  const save = useMutation({ mutationFn: () => api<Evaluation>(`/evaluations/${id}`, json("PUT", { actualValues: values })), onSuccess: refresh });
  const transition = useMutation({ mutationFn: (action: "submit" | "close") => api<Evaluation>(`/evaluations/${id}/${action}`, json("POST", {})), onSuccess: refresh });
  if (evaluation.isLoading || users.isLoading || periods.isLoading) return <Loading />; if (evaluation.error || !evaluation.data) return <ErrorState error={evaluation.error} />;
  const data = evaluation.data; const user = users.data?.find((item) => item.id === data.userId); const period = periods.data?.find((item) => item.id === data.periodId); const editable = data.status === "draft" && Boolean(actor?.isManager) && !["Closed", "Archived"].includes(period?.status ?? "");
  const localScore = data.kpis.reduce((sum, kpi) => { const actual = values[kpi.key]; return sum + (actual === null || actual === undefined ? 0 : Math.min(actual / kpi.expectedValue, 1) * kpi.weight); }, 0);
  return <><PageHeader title="Employee evaluation" description={`${user?.name ?? "Employee"} · ${user?.title ?? ""}`} action={<div className="flex gap-2"><Badge tone="purple">{period?.name}</Badge><Badge tone={data.status === "draft" ? "amber" : "green"}>{data.status}</Badge></div>} />{(save.error || transition.error) && <div className="mb-4"><ErrorState error={save.error ?? transition.error} /></div>}<div className="mb-6 grid gap-4 sm:grid-cols-3"><div className="card p-5"><div className="text-sm text-gray-500">Total KPI score</div><div className="mt-2 text-3xl font-semibold">{(editable ? localScore : data.totalScore).toFixed(2)}%</div></div><div className="card p-5"><div className="text-sm text-gray-500">Quarterly bonus</div><div className="mt-2 text-3xl font-semibold">{(editable ? localScore * (period?.bonusFactor ?? 0) : data.bonusPercentage).toFixed(2)}%</div></div><div className="card p-5"><div className="text-sm text-gray-500">Completed KPIs</div><div className="mt-2 text-3xl font-semibold">{Object.values(values).filter((value) => value !== null).length} / {data.kpis.length}</div></div></div><div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead><tr><th className="table-head">KPI</th><th className="table-head">Expected</th><th className="table-head">Actual</th><th className="table-head">Weight</th><th className="table-head">Score</th></tr></thead><tbody>{data.kpis.map((kpi) => { const actual = values[kpi.key]; const score = actual === null || actual === undefined ? 0 : Math.min(actual / kpi.expectedValue, 1) * kpi.weight; return <tr key={kpi.key}><td className="table-cell"><div className="font-semibold text-gray-900">{kpi.key} · {kpi.name}</div><div className="max-w-lg text-xs text-gray-500">{kpi.description}</div></td><td className="table-cell">{kpi.expectedValue}</td><td className="table-cell"><Input aria-label={`${kpi.key} actual value`} className="w-28" disabled={!editable} type="number" min="0" max={kpi.dataType === "percentage" ? 100 : undefined} step="0.01" value={actual ?? ""} onChange={(e) => setValues({ ...values, [kpi.key]: e.target.value === "" ? null : Number(e.target.value) })} /></td><td className="table-cell">{kpi.weight}%</td><td className="table-cell font-semibold">{score.toFixed(2)}</td></tr>; })}</tbody></table></div>{actor?.isManager && <div className="flex flex-wrap justify-end gap-3 border-t border-gray-200 p-5">{editable && <><Button variant="secondary" disabled={save.isPending} onClick={() => save.mutate()}>{save.isPending ? "Saving…" : "Save draft"}</Button><Button disabled={transition.isPending || Object.values(values).some((value) => value === null)} onClick={() => transition.mutate("submit")}>Submit evaluation</Button></>}{data.status === "submitted" && <Button onClick={() => transition.mutate("close")}>Close evaluation</Button>}</div>}</div></>;
}
