import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { Period, PeriodInput, PeriodStatus } from "@kpi/contracts";
import { useActor } from "../context/actor-context";
import { api, json } from "../lib/api";
import { Badge, Button, ErrorState, Input, Loading, Modal, PageHeader, Select } from "../components/ui";

const statuses: PeriodStatus[] = ["Draft", "Published", "Active", "Closed", "Archived"];
const initial: PeriodInput = { type: "quarterly", year: 2026, name: "Q4 2026", startDate: "2026-10-01T00:00:00.000Z", endDate: "2026-12-31T23:59:59.000Z", status: "Draft", bonusFactor: 0.25 };
const dateInput = (iso: string) => iso.slice(0, 10);
const toIso = (date: string, end = false) => `${date}T${end ? "23:59:59" : "00:00:00"}.000Z`;

export function PeriodsPage() {
  const { actorId, actor } = useActor(); const client = useQueryClient(); const [open, setOpen] = useState(false); const [form, setForm] = useState<PeriodInput>(initial);
  const query = useQuery({ queryKey: ["periods", actorId], queryFn: () => api<Period[]>("/periods") });
  const create = useMutation({ mutationFn: () => api<Period>("/periods", json("POST", form)), onSuccess: () => { setOpen(false); void client.invalidateQueries(); } });
  const advance = useMutation({ mutationFn: (period: Period) => { const next = statuses[statuses.indexOf(period.status) + 1]; return api<Period>(`/periods/${period.id}`, json("PUT", { ...period, status: next })); }, onSuccess: () => void client.invalidateQueries() });
  const root = actor?.isManager && actor.managerId === null;
  if (query.isLoading) return <Loading />; if (query.error) return <ErrorState error={query.error} />;
  return <><PageHeader title="Evaluation periods" description="Control monthly and quarterly evaluation windows and bonus policy." action={root ? <Button onClick={() => setOpen(true)}>+ New period</Button> : undefined} /><div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead><tr><th className="table-head">Period</th><th className="table-head">Type</th><th className="table-head">Dates</th><th className="table-head">Bonus factor</th><th className="table-head">Status</th><th className="table-head"></th></tr></thead><tbody>{query.data?.sort((a, b) => b.startDate.localeCompare(a.startDate)).map((period) => { const next = statuses[statuses.indexOf(period.status) + 1]; return <tr key={period.id}><td className="table-cell font-semibold text-gray-900">{period.name}</td><td className="table-cell capitalize">{period.type}</td><td className="table-cell">{new Date(period.startDate).toLocaleDateString()} – {new Date(period.endDate).toLocaleDateString()}</td><td className="table-cell">{(period.bonusFactor * 100).toFixed(0)}%</td><td className="table-cell"><Badge tone={period.status === "Active" ? "green" : period.status === "Draft" ? "amber" : "gray"}>{period.status}</Badge></td><td className="table-cell text-right">{root && next && <Button variant="secondary" onClick={() => advance.mutate(period)} disabled={advance.isPending}>Move to {next}</Button>}</td></tr>; })}</tbody></table></div></div>
    <Modal open={open} title="Create evaluation period" onClose={() => setOpen(false)}><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); create.mutate(); }}>{create.error && <ErrorState error={create.error} />}<div className="grid gap-4 sm:grid-cols-2"><label><span className="label">Type</span><Select value={form.type} onChange={(e) => { const type = e.target.value as PeriodInput["type"]; setForm({ ...form, type, bonusFactor: type === "quarterly" ? 0.25 : 0 }); }}><option value="quarterly">Quarterly</option><option value="monthly">Monthly</option></Select></label><label><span className="label">Year</span><Input type="number" value={form.year} onChange={(e) => setForm({ ...form, year: Number(e.target.value) })} /></label></div><label><span className="label">Name</span><Input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><div className="grid gap-4 sm:grid-cols-2"><label><span className="label">Start date</span><Input type="date" value={dateInput(form.startDate)} onChange={(e) => setForm({ ...form, startDate: toIso(e.target.value) })} /></label><label><span className="label">End date</span><Input type="date" value={dateInput(form.endDate)} onChange={(e) => setForm({ ...form, endDate: toIso(e.target.value, true) })} /></label></div><label><span className="label">Bonus factor</span><Input type="number" min="0" max="1" step="0.01" value={form.bonusFactor} onChange={(e) => setForm({ ...form, bonusFactor: Number(e.target.value) })} /><span className="mt-1 block text-xs text-gray-500">0.25 means 25% of the final score.</span></label><div className="flex justify-end"><Button disabled={create.isPending}>{create.isPending ? "Creating…" : "Create period"}</Button></div></form></Modal>
  </>;
}
