import { useEffect, useMemo, useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import type { KpiOverride, KpiTemplate, PerformancePoint, User, UserInput } from "@kpi/contracts";
import { useActor } from "../context/actor-context";
import { api, json } from "../lib/api";
import { Badge, Button, Empty, ErrorState, Input, Loading, Modal, PageHeader, Select, Switch } from "../components/ui";

const emptyUser = (managerId: string): UserInput => ({ name: "", email: "", title: "", isManager: false, managerId, status: "active", kpiTemplateId: null, kpiOverrides: [] });

export function UsersPage() {
  const { actorId, actor } = useActor(); const client = useQueryClient();
  const query = useQuery({ queryKey: ["users", actorId], queryFn: () => api<User[]>("/users") });
  const [editing, setEditing] = useState<User | null | "new">(null);
  const mutation = useMutation({ mutationFn: ({ id, value }: { id?: string; value: UserInput }) => api<User>(id ? `/users/${id}` : "/users", json(id ? "PUT" : "POST", value)), onSuccess: () => { setEditing(null); void client.invalidateQueries(); } });
  if (query.isLoading) return <Loading />; if (query.error) return <ErrorState error={query.error} />;
  const canManage = Boolean(actor?.isManager);
  return <><PageHeader title="People" description="Manage employees, managers, reporting lines, and active status." action={canManage ? <Button onClick={() => setEditing("new")}>+ Add user</Button> : undefined} />
    <div className="card overflow-hidden">{query.data?.length ? <div className="overflow-x-auto"><table className="w-full"><thead><tr><th className="table-head">Person</th><th className="table-head">Role</th><th className="table-head">Type</th><th className="table-head">Status</th><th className="table-head"><span className="sr-only">Actions</span></th></tr></thead><tbody>{query.data.map((user) => <tr key={user.id}><td className="table-cell"><div className="font-semibold text-gray-900">{user.name}</div><div className="text-xs text-gray-500">{user.email}</div></td><td className="table-cell">{user.title}</td><td className="table-cell"><Badge tone={user.isManager ? "purple" : "gray"}>{user.isManager ? "Manager" : "Employee"}</Badge></td><td className="table-cell"><Badge tone={user.status === "active" ? "green" : "red"}>{user.status}</Badge></td><td className="table-cell text-right"><Link className="mr-4 font-semibold text-brand-700" to={`/users/${user.id}`}>View</Link>{canManage && user.id !== actorId && <button className="font-semibold text-gray-600 hover:text-gray-900" onClick={() => setEditing(user)}>Edit</button>}</td></tr>)}</tbody></table></div> : <div className="p-5"><Empty title="No users found" text="Create a user to start building the organization." /></div>}</div>
    <Modal open={editing !== null} title={editing === "new" ? "Add user" : "Edit user"} onClose={() => setEditing(null)}><UserForm initial={editing === "new" ? emptyUser(actorId) : editing ?? emptyUser(actorId)} users={query.data ?? []} busy={mutation.isPending} error={mutation.error} onSubmit={(value) => mutation.mutate({ id: editing !== "new" && editing ? editing.id : undefined, value })} /></Modal>
  </>;
}

function UserForm({ initial, users, busy, error, onSubmit }: { initial: UserInput; users: User[]; busy: boolean; error: Error | null; onSubmit: (value: UserInput) => void }) {
  const [form, setForm] = useState<UserInput>(initial);
  const update = <K extends keyof UserInput>(key: K, value: UserInput[K]) => setForm((old) => ({ ...old, [key]: value }));
  return <form onSubmit={(event) => { event.preventDefault(); onSubmit(form); }} className="space-y-5">{error && <ErrorState error={error} />}<div className="grid gap-4 sm:grid-cols-2"><label><span className="label">Full name</span><Input required value={form.name} onChange={(e) => update("name", e.target.value)} /></label><label><span className="label">Email</span><Input type="email" required value={form.email} onChange={(e) => update("email", e.target.value)} /></label></div><label><span className="label">Role / title</span><Input required value={form.title} onChange={(e) => update("title", e.target.value)} /></label><label><span className="label">Manager</span><Select value={form.managerId ?? ""} onChange={(e) => update("managerId", e.target.value || null)}><option value="">No manager (root)</option>{users.filter((u) => u.isManager && u.status === "active").map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</Select></label><div className="rounded-lg border border-gray-200 p-4"><Switch checked={form.isManager} onChange={(value) => update("isManager", value)} label="Is Manager" /><p className="mt-2 text-xs text-gray-500">Managers can lead employees and other managers beneath them.</p></div><div className="rounded-lg border border-gray-200 p-4"><Switch checked={form.status === "active"} onChange={(value) => update("status", value ? "active" : "inactive")} label="Active user" /></div><div className="flex justify-end"><Button type="submit" disabled={busy}>{busy ? "Saving…" : "Save user"}</Button></div></form>;
}

export function UserDetailsPage() {
  const { id = "" } = useParams(); const { actorId, actor } = useActor(); const client = useQueryClient();
  const canManage = Boolean(actor?.isManager && actor.id !== id);
  const user = useQuery({ queryKey: ["user", actorId, id], queryFn: () => api<User>(`/users/${id}`) });
  const templates = useQuery({ queryKey: ["templates", actorId], queryFn: () => api<KpiTemplate[]>("/kpi-templates"), enabled: canManage });
  const history = useQuery({ queryKey: ["history", actorId, id], queryFn: () => api<PerformancePoint[]>(`/users/${id}/performance-history`) });
  const [templateId, setTemplateId] = useState(""); const [overrides, setOverrides] = useState<KpiOverride[]>([]);
  useEffect(() => { if (user.data) { setTemplateId(user.data.kpiTemplateId ?? ""); setOverrides(user.data.kpiOverrides ?? []); } }, [user.data]);
  const assign = useMutation({ mutationFn: () => api<User>(`/users/${id}/kpi-assignment`, json("PUT", { templateId, overrides })), onSuccess: () => void client.invalidateQueries(), });
  const selected = templates.data?.find((item) => item.id === templateId);
  if (user.isLoading || (canManage && templates.isLoading)) return <Loading />; if (user.error || !user.data) return <ErrorState error={user.error} />;
  const setOverride = (key: string, field: "expectedValue" | "weight", value: number) => setOverrides((current) => [...current.filter((item) => item.key !== key), { ...(current.find((item) => item.key === key) ?? { key }), [field]: value }]);
  return <><PageHeader title={user.data.name} description={user.data.title} /><div className="grid gap-6 xl:grid-cols-[360px_1fr]"><div className="space-y-6"><section className="card p-6"><div className="mb-5 grid h-14 w-14 place-items-center rounded-full bg-brand-100 text-lg font-semibold text-brand-700">{user.data.name.split(" ").map((p) => p[0]).slice(0, 2).join("")}</div><dl className="space-y-4 text-sm"><div><dt className="text-gray-500">Email</dt><dd className="font-medium">{user.data.email}</dd></div><div><dt className="text-gray-500">User type</dt><dd className="mt-1"><Badge tone={user.data.isManager ? "purple" : "gray"}>{user.data.isManager ? "Manager" : "Employee"}</Badge></dd></div><div><dt className="text-gray-500">Status</dt><dd className="mt-1"><Badge tone={user.data.status === "active" ? "green" : "red"}>{user.data.status}</Badge></dd></div></dl></section><section className="card p-6"><h2 className="font-semibold">Performance history</h2><div className="mt-4 space-y-3">{history.data?.map((point) => <div key={point.evaluation.id} className="flex justify-between text-sm"><span className="text-gray-600">{point.period.name}</span><strong>{point.evaluation.totalScore.toFixed(2)}%</strong></div>)}{!history.data?.length && <p className="text-sm text-gray-500">No completed evaluations.</p>}</div></section></div>
    <section className="card p-6"><h2 className="font-semibold">KPI assignment</h2><p className="mb-5 text-sm text-gray-500">Assign an active template and optionally tailor expectations or weights.</p>{assign.error && <div className="mb-4"><ErrorState error={assign.error} /></div>}<label><span className="label">Template</span><Select disabled={!canManage} value={templateId} onChange={(e) => { setTemplateId(e.target.value); setOverrides([]); }}><option value="">Select a template</option>{templates.data?.filter((item) => item.status === "active").map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></label>{selected && <div className="mt-5 overflow-x-auto"><table className="w-full"><thead><tr><th className="table-head">KPI</th><th className="table-head">Expected</th><th className="table-head">Weight</th></tr></thead><tbody>{selected.items.filter((item) => item.enabled).map((item) => { const override = overrides.find((entry) => entry.key === item.key); return <tr key={item.key}><td className="table-cell font-semibold">{item.key}</td><td className="table-cell"><Input disabled={!canManage} type="number" step="0.01" value={override?.expectedValue ?? item.expectedValue} onChange={(e) => setOverride(item.key, "expectedValue", Number(e.target.value))} className="w-28" /></td><td className="table-cell"><Input disabled={!canManage} type="number" step="0.01" value={override?.weight ?? item.weight} onChange={(e) => setOverride(item.key, "weight", Number(e.target.value))} className="w-28" /></td></tr>; })}</tbody></table></div>}{canManage && <div className="mt-5 flex justify-end"><Button disabled={!templateId || assign.isPending} onClick={() => assign.mutate()}>{assign.isPending ? "Saving…" : "Save assignment"}</Button></div>}</section></div></>;
}
